"""Initial KontentPypper models

Revision ID: 17c2bc98d011
Revises: 
Create Date: 2026-03-04 09:27:37.981166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17c2bc98d011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('last_login_method', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('posts_used', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('posts_limit', sa.Integer(), server_default=sa.text('10'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_on_post_success', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('email_on_post_failure', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('email_weekly_analytics', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('content_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('subreddit_name', sa.String(), nullable=True),
    sa.Column('rss_feed_url', sa.String(), nullable=True),
    sa.Column('keywords_filter', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('exclude_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('min_score', sa.Integer(), server_default=sa.text('100'), nullable=True),
    sa.Column('max_age_hours', sa.Integer(), server_default=sa.text('24'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('fetch_interval_hours', sa.Integer(), server_default=sa.text('6'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_sources_id'), 'content_sources', ['id'], unique=False)
    op.create_index(op.f('ix_content_sources_user_id'), 'content_sources', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('enhanced_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('video_urls', sa.Text(), nullable=True),
    sa.Column('audio_file_url', sa.String(), nullable=True),
    sa.Column('platform_specific_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'processing'"), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_scheduled_for'), 'posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('social_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('oauth_token_secret', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_avatar_url', sa.String(), nullable=True),
    sa.Column('platform_username', sa.String(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('facebook_page_id', sa.String(), nullable=True),
    sa.Column('facebook_page_name', sa.String(), nullable=True),
    sa.Column('facebook_page_access_token', sa.Text(), nullable=True),
    sa.Column('facebook_page_category', sa.String(), nullable=True),
    sa.Column('facebook_page_picture', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_connections_id'), 'social_connections', ['id'], unique=False)
    op.create_index(op.f('ix_social_connections_platform'), 'social_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_social_connections_user_id'), 'social_connections', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('template_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), server_default=sa.text("'#6366F1'"), nullable=True),
    sa.Column('icon', sa.String(), server_default=sa.text("'folder'"), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_folders_id'), 'template_folders', ['id'], unique=False)
    op.create_index(op.f('ix_template_folders_user_id'), 'template_folders', ['user_id'], unique=False)
    op.create_table('user_analytics_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_posts', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_engagements', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_impressions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('platform_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', 'start_date', name='uq_user_period_start')
    )
    op.create_index(op.f('ix_user_analytics_summaries_id'), 'user_analytics_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_period'), 'user_analytics_summaries', ['period'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_start_date'), 'user_analytics_summaries', ['start_date'], unique=False)
    op.create_index(op.f('ix_user_analytics_summaries_user_id'), 'user_analytics_summaries', ['user_id'], unique=False)
    op.create_table('post_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('impressions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('reach', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('shares', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('saves', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('clicks', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('platform_specific_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engagement_rate', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'platform', name='uq_post_platform')
    )
    op.create_index(op.f('ix_post_analytics_fetched_at'), 'post_analytics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_post_analytics_id'), 'post_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_post_analytics_platform'), 'post_analytics', ['platform'], unique=False)
    op.create_index(op.f('ix_post_analytics_post_id'), 'post_analytics', ['post_id'], unique=False)
    op.create_table('post_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('platform_post_url', sa.String(), nullable=True),
    sa.Column('content_used', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_results_id'), 'post_results', ['id'], unique=False)
    op.create_index(op.f('ix_post_results_post_id'), 'post_results', ['post_id'], unique=False)
    op.create_table('post_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_variations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_platforms', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('tone', sa.String(), server_default=sa.text("'engaging'"), nullable=True),
    sa.Column('suggested_hashtags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_media_type', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('is_premium', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('success_rate', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('avg_engagement', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('color_scheme', sa.String(), server_default=sa.text("'#3B82F6'"), nullable=True),
    sa.Column('icon', sa.String(), server_default=sa.text("'sparkles'"), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['template_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_templates_category'), 'post_templates', ['category'], unique=False)
    op.create_index(op.f('ix_post_templates_id'), 'post_templates', ['id'], unique=False)
    op.create_index(op.f('ix_post_templates_name'), 'post_templates', ['name'], unique=False)
    op.create_index(op.f('ix_post_templates_user_id'), 'post_templates', ['user_id'], unique=False)
    op.create_table('video_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_style', sa.String(), server_default=sa.text("'ai_images_motion'"), nullable=True),
    sa.Column('aspect_ratio', sa.String(), server_default=sa.text("'9:16'"), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), server_default=sa.text('60'), nullable=True),
    sa.Column('tts_provider', sa.String(), server_default=sa.text("'openai'"), nullable=True),
    sa.Column('tts_voice', sa.String(), server_default=sa.text("'alloy'"), nullable=True),
    sa.Column('tts_speed', sa.Float(), server_default=sa.text('1.0'), nullable=True),
    sa.Column('background_music_url', sa.String(), nullable=True),
    sa.Column('music_volume', sa.Float(), server_default=sa.text('0.3'), nullable=True),
    sa.Column('caption_style', sa.String(), server_default=sa.text("'modern'"), nullable=True),
    sa.Column('caption_font', sa.String(), server_default=sa.text("'Montserrat'"), nullable=True),
    sa.Column('caption_color', sa.String(), server_default=sa.text("'#FFFFFF'"), nullable=True),
    sa.Column('caption_position', sa.String(), server_default=sa.text("'bottom'"), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('videos_per_day', sa.Integer(), server_default=sa.text('2'), nullable=True),
    sa.Column('preferred_times', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('videos_generated', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_generation', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['content_source_id'], ['content_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_campaigns_id'), 'video_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_video_campaigns_user_id'), 'video_campaigns', ['user_id'], unique=False)
    op.create_table('template_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('likes', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('comments', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('shares', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('engagement_rate', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['post_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_analytics_id'), 'template_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_template_analytics_template_id'), 'template_analytics', ['template_id'], unique=False)
    op.create_table('video_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_title', sa.String(), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('script_scenes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('narration_url', sa.String(), nullable=True),
    sa.Column('narration_duration', sa.Float(), nullable=True),
    sa.Column('image_prompts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_post_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['video_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_campaign_id'), 'video_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_video_jobs_id'), 'video_jobs', ['id'], unique=False)
    op.create_table('story_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('num_comments', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('used_in_job_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_in_job_id'], ['video_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_contents_id'), 'story_contents', ['id'], unique=False)
    op.create_index(op.f('ix_story_contents_user_id'), 'story_contents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_contents_user_id'), table_name='story_contents')
    op.drop_index(op.f('ix_story_contents_id'), table_name='story_contents')
    op.drop_table('story_contents')
    op.drop_index(op.f('ix_video_jobs_id'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_campaign_id'), table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index(op.f('ix_template_analytics_template_id'), table_name='template_analytics')
    op.drop_index(op.f('ix_template_analytics_id'), table_name='template_analytics')
    op.drop_table('template_analytics')
    op.drop_index(op.f('ix_video_campaigns_user_id'), table_name='video_campaigns')
    op.drop_index(op.f('ix_video_campaigns_id'), table_name='video_campaigns')
    op.drop_table('video_campaigns')
    op.drop_index(op.f('ix_post_templates_user_id'), table_name='post_templates')
    op.drop_index(op.f('ix_post_templates_name'), table_name='post_templates')
    op.drop_index(op.f('ix_post_templates_id'), table_name='post_templates')
    op.drop_index(op.f('ix_post_templates_category'), table_name='post_templates')
    op.drop_table('post_templates')
    op.drop_index(op.f('ix_post_results_post_id'), table_name='post_results')
    op.drop_index(op.f('ix_post_results_id'), table_name='post_results')
    op.drop_table('post_results')
    op.drop_index(op.f('ix_post_analytics_post_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_platform'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_fetched_at'), table_name='post_analytics')
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_user_analytics_summaries_user_id'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_start_date'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_period'), table_name='user_analytics_summaries')
    op.drop_index(op.f('ix_user_analytics_summaries_id'), table_name='user_analytics_summaries')
    op.drop_table('user_analytics_summaries')
    op.drop_index(op.f('ix_template_folders_user_id'), table_name='template_folders')
    op.drop_index(op.f('ix_template_folders_id'), table_name='template_folders')
    op.drop_table('template_folders')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_social_connections_user_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_platform'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_id'), table_name='social_connections')
    op.drop_table('social_connections')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_for'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_content_sources_user_id'), table_name='content_sources')
    op.drop_index(op.f('ix_content_sources_id'), table_name='content_sources')
    op.drop_table('content_sources')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
