"""Add AssetLibrary table

Revision ID: 9eb226871692
Revises: e76da06b1cef
Create Date: 2026-03-10 21:02:27.280524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb226871692'
down_revision: Union[str, Sequence[str], None] = 'e76da06b1cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('platforms_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_library_id'), 'asset_library', ['id'], unique=False)
    op.create_index(op.f('ix_asset_library_user_id'), 'asset_library', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_library_user_id'), table_name='asset_library')
    op.drop_index(op.f('ix_asset_library_id'), table_name='asset_library')
    op.drop_table('asset_library')
    # ### end Alembic commands ###
