"""Added niche column

Revision ID: e76da06b1cef
Revises: eabb4b4f69e9
Create Date: 2026-03-10 06:58:37.237525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76da06b1cef'
down_revision: Union[str, Sequence[str], None] = 'eabb4b4f69e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('niche', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'niche')
    # ### end Alembic commands ###
